export const athletes = {
  23: {
    female: [
      {
        place: "1",
        name: "Sofia Gomez Villafane",
        gender: "Female",
        "sea otter": "35",
        unbound: "35",
        crusher: "35",
        leadville: "35",
        chequamegon: "33",
        "the rad": "(0)",
        "big sugar": "(12)",
        "total points": "173",
      },
      {
        place: "2",
        name: "Alexis Skarda",
        gender: "Female",
        "sea otter": "34",
        unbound: "(0)",
        crusher: "(29)",
        leadville: "33",
        chequamegon: "34",
        "the rad": "34",
        "big sugar": "32",
        "total points": "167",
      },
      {
        place: "3",
        name: "Haley Smith",
        gender: "Female",
        "sea otter": "33",
        unbound: "31",
        crusher: "33",
        leadville: "31",
        chequamegon: "32",
        "the rad": "(0)",
        "big sugar": "(30)",
        "total points": "160",
      },
      {
        place: "4",
        name: "Sarah Sturm",
        gender: "Female",
        "sea otter": "32",
        unbound: "34",
        crusher: "31",
        leadville: "29",
        chequamegon: "(27)",
        "the rad": "(25)",
        "big sugar": "31",
        "total points": "157",
      },
      {
        place: "5",
        name: "Lauren De Crescenzo",
        gender: "Female",
        "sea otter": "(18)",
        unbound: "(0)",
        crusher: "34",
        leadville: "24",
        chequamegon: "28",
        "the rad": "35",
        "big sugar": "35",
        "total points": "156",
      },
      {
        place: "6",
        name: "Jenna Rinehart",
        gender: "Female",
        "sea otter": "31",
        unbound: "(0)",
        crusher: "(21)",
        leadville: "28",
        chequamegon: "30",
        "the rad": "27",
        "big sugar": "33",
        "total points": "149",
      },
      {
        place: "7",
        name: "Paige Onweller",
        gender: "Female",
        "sea otter": "(21)",
        unbound: "(0)",
        crusher: "32",
        leadville: "25",
        chequamegon: "25",
        "the rad": "32",
        "big sugar": "34",
        "total points": "148",
      },
      {
        place: "8",
        name: "Crystal Anthony",
        gender: "Female",
        "sea otter": "29",
        unbound: "(0)",
        crusher: "24",
        leadville: "30",
        chequamegon: "26",
        "the rad": "33",
        "big sugar": "(13)",
        "total points": "142",
      },
      {
        place: "9",
        name: "Hannah Otto",
        gender: "Female",
        "sea otter": "30",
        unbound: "(0)",
        crusher: "25",
        leadville: "32",
        chequamegon: "31",
        "the rad": "(0)",
        "big sugar": "17",
        "total points": "135",
      },
      {
        place: "10",
        name: "Deanna Mayles",
        gender: "Female",
        "sea otter": "24",
        unbound: "(0)",
        crusher: "26",
        leadville: "(23)",
        chequamegon: "29",
        "the rad": "29",
        "big sugar": "25",
        "total points": "133",
      },
      {
        place: "11",
        name: "Ellen Campbell",
        gender: "Female",
        "sea otter": "25",
        unbound: "23",
        crusher: "22",
        leadville: "27",
        chequamegon: "(20)",
        "the rad": "30",
        "big sugar": "(20)",
        "total points": "127",
      },
      {
        place: "12",
        name: "Caroline Tory",
        gender: "Female",
        "sea otter": "23",
        unbound: "27",
        crusher: "(17)",
        leadville: "21",
        chequamegon: "(0)",
        "the rad": "28",
        "big sugar": "26",
        "total points": "125",
      },
      {
        place: "13",
        name: "Sarah Max",
        gender: "Female",
        "sea otter": "22",
        unbound: "26",
        crusher: "27",
        leadville: "(17)",
        chequamegon: "(19)",
        "the rad": "26",
        "big sugar": "23",
        "total points": "124",
      },
      {
        place: "14",
        name: "Heather Jackson",
        gender: "Female",
        "sea otter": "19",
        unbound: "22",
        crusher: "(0)",
        leadville: "22",
        chequamegon: "(0)",
        "the rad": "31",
        "big sugar": "28",
        "total points": "122",
      },
      {
        place: "15",
        name: "Emily Newsom",
        gender: "Female",
        "sea otter": "26",
        unbound: "(0)",
        crusher: "28",
        leadville: "13",
        chequamegon: "(0)",
        "the rad": "24",
        "big sugar": "27",
        "total points": "118",
      },
      {
        place: "16",
        name: "Emma Grant",
        gender: "Female",
        "sea otter": "(0)",
        unbound: "24",
        crusher: "23",
        leadville: "15",
        chequamegon: "(0)",
        "the rad": "21",
        "big sugar": "29",
        "total points": "112",
      },
      {
        place: "17",
        name: "Angela Naeth",
        gender: "Female",
        "sea otter": "(0)",
        unbound: "28",
        crusher: "18",
        leadville: "(14)",
        chequamegon: "17",
        "the rad": "15",
        "big sugar": "21",
        "total points": "99",
      },
      {
        place: "17",
        name: "Ruth Edwards",
        gender: "Female",
        "sea otter": "0",
        unbound: "0",
        crusher: "30",
        leadville: "34",
        chequamegon: "35",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "99",
      },
      {
        place: "17",
        name: "Anna Yamauchi",
        gender: "Female",
        "sea otter": "(0)",
        unbound: "17",
        crusher: "(0)",
        leadville: "26",
        chequamegon: "22",
        "the rad": "19",
        "big sugar": "15",
        "total points": "99",
      },
      {
        place: "20",
        name: "Maude Farrell",
        gender: "Female",
        "sea otter": "28",
        unbound: "0",
        crusher: "20",
        leadville: "(0)",
        chequamegon: "24",
        "the rad": "(0)",
        "big sugar": "24",
        "total points": "96",
      },
      {
        place: "21",
        name: "Danni Shrosbree",
        gender: "Female",
        "sea otter": "11",
        unbound: "33",
        crusher: "8",
        leadville: "(0)",
        chequamegon: "(0)",
        "the rad": "18",
        "big sugar": "22",
        "total points": "92",
      },
      {
        place: "22",
        name: "Isabel King",
        gender: "Female",
        "sea otter": "13",
        unbound: "25",
        crusher: "(10)",
        leadville: "(0)",
        chequamegon: "18",
        "the rad": "22",
        "big sugar": "11",
        "total points": "89",
      },
      {
        place: "23",
        name: "Leah Van Der Linden",
        gender: "Female",
        "sea otter": "20",
        unbound: "30",
        crusher: "19",
        leadville: "16",
        chequamegon: "0",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "85",
      },
      {
        place: "24",
        name: "Ella Bloor",
        gender: "Female",
        "sea otter": "27",
        unbound: "(0)",
        crusher: "14",
        leadville: "7",
        chequamegon: "15",
        "the rad": "20",
        "big sugar": "(6)",
        "total points": "83",
      },
      {
        place: "24",
        name: "Chelsea Bolton",
        gender: "Female",
        "sea otter": "15",
        unbound: "(0)",
        crusher: "16",
        leadville: "19",
        chequamegon: "(0)",
        "the rad": "23",
        "big sugar": "10",
        "total points": "83",
      },
      {
        place: "26",
        name: "Caroline Mani",
        gender: "Female",
        "sea otter": "16",
        unbound: "20",
        crusher: "9",
        leadville: "18",
        chequamegon: "(0)",
        "the rad": "(0)",
        "big sugar": "18",
        "total points": "81",
      },
      {
        place: "27",
        name: "Rebecca Fahringer",
        gender: "Female",
        "sea otter": "10",
        unbound: "32",
        crusher: "0",
        leadville: "10",
        chequamegon: "23",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "75",
      },
      {
        place: "27",
        name: "Catherine Colyn",
        gender: "Female",
        "sea otter": "0",
        unbound: "(0)",
        crusher: "15",
        leadville: "20",
        chequamegon: "21",
        "the rad": "(0)",
        "big sugar": "19",
        "total points": "75",
      },
      {
        place: "29",
        name: "Hannah Shell",
        gender: "Female",
        "sea otter": "(8)",
        unbound: "19",
        crusher: "(0)",
        leadville: "12",
        chequamegon: "12",
        "the rad": "17",
        "big sugar": "14",
        "total points": "74",
      },
      {
        place: "30",
        name: "Julie Momber",
        gender: "Female",
        "sea otter": "12",
        unbound: "16",
        crusher: "12",
        leadville: "(11)",
        chequamegon: "16",
        "the rad": "(0)",
        "big sugar": "16",
        "total points": "72",
      },
      {
        place: "31",
        name: "Jessica Mullins",
        gender: "Female",
        "sea otter": "14",
        unbound: "15",
        crusher: "(0)",
        leadville: "9",
        chequamegon: "13",
        "the rad": "16",
        "big sugar": "(9)",
        "total points": "67",
      },
      {
        place: "32",
        name: "Holly Mathews",
        gender: "Female",
        "sea otter": "6",
        unbound: "29",
        crusher: "13",
        leadville: "8",
        chequamegon: "0",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "56",
      },
      {
        place: "33",
        name: "Starla Teddergreen",
        gender: "Female",
        "sea otter": "9",
        unbound: "21",
        crusher: "0",
        leadville: "(0)",
        chequamegon: "14",
        "the rad": "(0)",
        "big sugar": "8",
        "total points": "52",
      },
      {
        place: "34",
        name: "Raylyn Nuss",
        gender: "Female",
        "sea otter": "17",
        unbound: "18",
        crusher: "11",
        leadville: "0",
        chequamegon: "0",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "46",
      },
      {
        place: "35",
        name: "Isabella Hyser",
        gender: "Female",
        "sea otter": "7",
        unbound: "14",
        crusher: "(0)",
        leadville: "6",
        chequamegon: "11",
        "the rad": "(0)",
        "big sugar": "7",
        "total points": "45",
      },
    ],
    male: [
      {
        place: "1",
        name: "Keegan Swenson",
        gender: "Male",
        "sea otter": "35",
        unbound: "35",
        crusher: "35",
        leadville: "35",
        chequamegon: "34",
        "the rad": "(0)",
        "big sugar": "(33)",
        "total points": "174",
      },
      {
        place: "2",
        name: "Alexey Vermeulen",
        gender: "Male",
        "sea otter": "(15)",
        unbound: "28",
        crusher: "(28)",
        leadville: "34",
        chequamegon: "35",
        "the rad": "35",
        "big sugar": "34",
        "total points": "166",
      },
      {
        place: "3",
        name: "Cole Paton",
        gender: "Male",
        "sea otter": "33",
        unbound: "(17)",
        crusher: "31",
        leadville: "33",
        chequamegon: "33",
        "the rad": "(20)",
        "big sugar": "32",
        "total points": "162",
      },
      {
        place: "4",
        name: "Russell Finsterwald",
        gender: "Male",
        "sea otter": "34",
        unbound: "33",
        crusher: "27",
        leadville: "30",
        chequamegon: "(20)",
        "the rad": "30",
        "big sugar": "(23)",
        "total points": "154",
      },
      {
        place: "5",
        name: "Lachlan Morton",
        gender: "Male",
        "sea otter": "(22)",
        unbound: "34",
        crusher: "32",
        leadville: "28",
        chequamegon: "(15)",
        "the rad": "32",
        "big sugar": "27",
        "total points": "153",
      },
      {
        place: "6",
        name: "Peter Stetina",
        gender: "Male",
        "sea otter": "(17)",
        unbound: "32",
        crusher: "34",
        leadville: "22",
        chequamegon: "24",
        "the rad": "34",
        "big sugar": "(16)",
        "total points": "146",
      },
      {
        place: "7",
        name: "Brendan Johnston",
        gender: "Male",
        "sea otter": "30",
        unbound: "(0)",
        crusher: "(10)",
        leadville: "21",
        chequamegon: "25",
        "the rad": "33",
        "big sugar": "35",
        "total points": "144",
      },
      {
        place: "8",
        name: "Alex Howes",
        gender: "Male",
        "sea otter": "20",
        unbound: "(20)",
        crusher: "(18)",
        leadville: "26",
        chequamegon: "30",
        "the rad": "31",
        "big sugar": "28",
        "total points": "135",
      },
      {
        place: "9",
        name: "Howard Grotts",
        gender: "Male",
        "sea otter": "29",
        unbound: "(18)",
        crusher: "19",
        leadville: "32",
        chequamegon: "23",
        "the rad": "(16)",
        "big sugar": "29",
        "total points": "132",
      },
      {
        place: "10",
        name: "Zach Calton",
        gender: "Male",
        "sea otter": "19",
        unbound: "30",
        crusher: "(14)",
        leadville: "31",
        chequamegon: "29",
        "the rad": "19",
        "big sugar": "(19)",
        "total points": "128",
      },
      {
        place: "10",
        name: "Konny Looser",
        gender: "Male",
        "sea otter": "32",
        unbound: "27",
        crusher: "22",
        leadville: "(0)",
        chequamegon: "27",
        "the rad": "(10)",
        "big sugar": "20",
        "total points": "128",
      },
      {
        place: "12",
        name: "Payson McElveen",
        gender: "Male",
        "sea otter": "(0)",
        unbound: "(0)",
        crusher: "26",
        leadville: "27",
        chequamegon: "32",
        "the rad": "9",
        "big sugar": "26",
        "total points": "120",
      },
      {
        place: "13",
        name: "Kyle Trudeau",
        gender: "Male",
        "sea otter": "23",
        unbound: "23",
        crusher: "23",
        leadville: "(0)",
        chequamegon: "(0)",
        "the rad": "25",
        "big sugar": "24",
        "total points": "118",
      },
      {
        place: "14",
        name: "Matthew Beers",
        gender: "Male",
        "sea otter": "0",
        unbound: "29",
        crusher: "33",
        leadville: "(0)",
        chequamegon: "26",
        "the rad": "28",
        "big sugar": "(0)",
        "total points": "116",
      },
      {
        place: "15",
        name: "Lance Haidet",
        gender: "Male",
        "sea otter": "21",
        unbound: "(0)",
        crusher: "21",
        leadville: "(0)",
        chequamegon: "28",
        "the rad": "29",
        "big sugar": "14",
        "total points": "113",
      },
      {
        place: "16",
        name: "Dylan Johnson",
        gender: "Male",
        "sea otter": "(14)",
        unbound: "25",
        crusher: "(15)",
        leadville: "23",
        chequamegon: "21",
        "the rad": "22",
        "big sugar": "21",
        "total points": "112",
      },
      {
        place: "17",
        name: "Tasman Nankervis",
        gender: "Male",
        "sea otter": "(0)",
        unbound: "(13)",
        crusher: "17",
        leadville: "15",
        chequamegon: "17",
        "the rad": "26",
        "big sugar": "30",
        "total points": "105",
      },
      {
        place: "18",
        name: "Nathan Spratt",
        gender: "Male",
        "sea otter": "(9)",
        unbound: "(0)",
        crusher: "30",
        leadville: "11",
        chequamegon: "12",
        "the rad": "27",
        "big sugar": "22",
        "total points": "102",
      },
      {
        place: "18",
        name: "Bradyn Lange",
        gender: "Male",
        "sea otter": "28",
        unbound: "0",
        crusher: "29",
        leadville: "30",
        chequamegon: "(0)",
        "the rad": "(0)",
        "big sugar": "15",
        "total points": "102",
      },
      {
        place: "20",
        name: "Logan Owen",
        gender: "Male",
        "sea otter": "0",
        unbound: "(0)",
        crusher: "25",
        leadville: "24",
        chequamegon: "31",
        "the rad": "21",
        "big sugar": "(0)",
        "total points": "101",
      },
      {
        place: "21",
        name: "Ian Lopez De San Roman",
        gender: "Male",
        "sea otter": "18",
        unbound: "(0)",
        crusher: "20",
        leadville: "(16)",
        chequamegon: "19",
        "the rad": "18",
        "big sugar": "25",
        "total points": "100",
      },
      {
        place: "22",
        name: "Andrew L'Esperance",
        gender: "Male",
        "sea otter": "31",
        unbound: "(0)",
        crusher: "(0)",
        leadville: "17",
        chequamegon: "22",
        "the rad": "15",
        "big sugar": "13",
        "total points": "98",
      },
      {
        place: "23",
        name: "Jack Odron",
        gender: "Male",
        "sea otter": "12",
        unbound: "22",
        crusher: "16",
        leadville: "25",
        chequamegon: "(5)",
        "the rad": "17",
        "big sugar": "(0)",
        "total points": "92",
      },
      {
        place: "24",
        name: "John Borstelmann",
        gender: "Male",
        "sea otter": "13",
        unbound: "12",
        crusher: "9",
        leadville: "(8)",
        chequamegon: "(6)",
        "the rad": "24",
        "big sugar": "31",
        "total points": "89",
      },
      {
        place: "25",
        name: "Kerry Werner",
        gender: "Male",
        "sea otter": "26",
        unbound: "21",
        crusher: "(0)",
        leadville: "9",
        chequamegon: "14",
        "the rad": "(8)",
        "big sugar": "18",
        "total points": "88",
      },
      {
        place: "26",
        name: "Ryan Standish",
        gender: "Male",
        "sea otter": "24",
        unbound: "15",
        crusher: "(0)",
        leadville: "19",
        chequamegon: "18",
        "the rad": "11",
        "big sugar": "(10)",
        "total points": "87",
      },
      {
        place: "27",
        name: "Tobin Ortenblad",
        gender: "Male",
        "sea otter": "27",
        unbound: "24",
        crusher: "(8)",
        leadville: "13",
        chequamegon: "10",
        "the rad": "(0)",
        "big sugar": "11",
        "total points": "85",
      },
      {
        place: "28",
        name: "Griffin Easter",
        gender: "Male",
        "sea otter": "(8)",
        unbound: "16",
        crusher: "24",
        leadville: "14",
        chequamegon: "13",
        "the rad": "13",
        "big sugar": "(9)",
        "total points": "80",
      },
      {
        place: "29",
        name: "Eric Brunner",
        gender: "Male",
        "sea otter": "(0)",
        unbound: "(0)",
        crusher: "12",
        leadville: "10",
        chequamegon: "11",
        "the rad": "23",
        "big sugar": "17",
        "total points": "73",
      },
      {
        place: "30",
        name: "Brennan Wertz",
        gender: "Male",
        "sea otter": "(10)",
        unbound: "(0)",
        crusher: "11",
        leadville: "18",
        chequamegon: "16",
        "the rad": "12",
        "big sugar": "12",
        "total points": "69",
      },
      {
        place: "31",
        name: "Adam Roberge",
        gender: "Male",
        "sea otter": "16",
        unbound: "31",
        crusher: "13",
        leadville: "0",
        chequamegon: "8",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "68",
      },
      {
        place: "32",
        name: "Taylor Lideen",
        gender: "Male",
        "sea otter": "25",
        unbound: "(0)",
        crusher: "(0)",
        leadville: "12",
        chequamegon: "9",
        "the rad": "14",
        "big sugar": "7",
        "total points": "67",
      },
      {
        place: "33",
        name: "Robert Britton",
        gender: "Male",
        "sea otter": "0",
        unbound: "26",
        crusher: "0",
        leadville: "20",
        chequamegon: "0",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "46",
      },
      {
        place: "34",
        name: "Kiel Reijnen",
        gender: "Male",
        "sea otter": "(0)",
        unbound: "14",
        crusher: "7",
        leadville: "7",
        chequamegon: "7",
        "the rad": "(0)",
        "big sugar": "8",
        "total points": "43",
      },
      {
        place: "35",
        name: "Innokenty Zavyalov",
        gender: "Male",
        "sea otter": "11",
        unbound: "19",
        crusher: "0",
        leadville: "0",
        chequamegon: "0",
        "the rad": "(0)",
        "big sugar": "(0)",
        "total points": "30",
      },
    ],
  },
};
