CREATE TABLE IF NOT EXISTS "all_star_team" (
    id serial primary key,
    team_id integer,
    first_male integer,
    second_male integer,
    third_male integer,
    fourth_male integer,
    fifth_male integer,
    first_female integer,
    second_female integer,
    third_female integer,
    fourth_female integer,
    fifth_female integer,
    constraint fk_team foreign key (team_id) references teams(id),
    constraint fk_first_male_all_star foreign key (first_male) references athletes(id),
    constraint fk_first_female_all_star foreign key (first_female) references athletes(id),
    constraint fk_second_male_all_star foreign key (second_male) references athletes(id),
    constraint fk_second_female_all_star foreign key (second_female) references athletes(id),
    constraint fk_third_male_all_star foreign key (third_male) references athletes(id),
    constraint fk_third_female_all_star foreign key (third_female) references athletes(id),
    constraint fk_fourth_male_all_star foreign key (fourth_male) references athletes(id),
    constraint fk_fourth_female_all_star foreign key (fourth_female) references athletes(id),
    constraint fk_fifth_male_all_star foreign key (fifth_male) references athletes(id),
    constraint fk_fifth_female_all_star foreign key (fifth_female) references athletes(id),
)
